/* This file is generated by generate_c_code.py script, do not modify. */
#include "config/include/carol/signals.h"
#include "config/include/carol/signals_info_mblk.h"
#include "config/include/carol/pins_io.h"
#include "config/include/carol/network_defaults.h"
