/* This file is generated by signals_to_c.py script, do not modify. */
OS_FLASH_MEM struct democar_t democar = 
{
  {
    {"exp", &ioboard_exp, 34, DEMOCAR_EXP_MBLK_SZ, (iocSignal*)&democar.exp.nc_nr},
    {0, 8, OS_STR, &ioboard_exp, OS_NULL}, /* nc_nr */
    {9, 25, OS_STR, &ioboard_exp, OS_NULL}, /* nc_net */
    {35, 65, OS_STR, &ioboard_exp, OS_NULL}, /* nc_connect */
    {101, 17, OS_STR, &ioboard_exp, OS_NULL}, /* nc_wifi */
    {119, 17, OS_STR, &ioboard_exp, OS_NULL}, /* nc_pass */
    {137, 48, OS_STR, &ioboard_exp, OS_NULL}, /* nc_ip */
    {186, 1, OS_CHAR, &ioboard_exp, OS_NULL}, /* nc_status */
    {188, 12, OS_STR, &ioboard_exp, OS_NULL}, /* si_package */
    {201, 7, OS_STR, &ioboard_exp, OS_NULL}, /* si_eosal */
    {209, 7, OS_STR, &ioboard_exp, OS_NULL}, /* si_iocom */
    {217, 8, OS_STR, &ioboard_exp, OS_NULL}, /* si_os */
    {226, 8, OS_STR, &ioboard_exp, OS_NULL}, /* si_osver */
    {235, 8, OS_STR, &ioboard_exp, OS_NULL}, /* si_arch */
    {244, 17, OS_STR, &ioboard_exp, OS_NULL}, /* si_hw */
    {262, 1, OS_UINT, &ioboard_exp, OS_NULL}, /* rm_malloc */
    {267, 1, OS_UINT, &ioboard_exp, OS_NULL}, /* rm_muse */
    {272, 1, OS_USHORT, &ioboard_exp, OS_NULL}, /* rm_threads */
    {275, 1, OS_USHORT, &ioboard_exp, OS_NULL}, /* rm_events */
    {278, 1, OS_USHORT, &ioboard_exp, OS_NULL}, /* rm_mutexes */
    {281, 1, OS_USHORT, &ioboard_exp, OS_NULL}, /* rm_sockets */
    {284, 1, OS_USHORT, &ioboard_exp, OS_NULL}, /* rm_connects */
    {287, 1, OS_LONG, &ioboard_exp, OS_NULL}, /* rm_tx_tcp */
    {296, 1, OS_LONG, &ioboard_exp, OS_NULL}, /* rm_rx_tcp */
    {305, 1, OS_LONG, &ioboard_exp, OS_NULL}, /* rm_tx_udp */
    {314, 1, OS_LONG, &ioboard_exp, OS_NULL}, /* rm_rx_udp */
    {323, 1, OS_LONG, &ioboard_exp, OS_NULL}, /* rm_tx_serial */
    {332, 1, OS_LONG, &ioboard_exp, OS_NULL}, /* rm_rx_serial */
    {341, 1, OS_FLOAT, &ioboard_exp, OS_NULL}, /* rm_aveloop */
    {346, 1, OS_FLOAT, &ioboard_exp, OS_NULL}, /* rm_maxloop */
    {351, 1, OS_UINT, &ioboard_exp, OS_NULL}, /* rm_boottime */
    {356, 1, OS_BOOLEAN|IOC_PIN_PTR, &ioboard_exp, &pins.outputs.LEFT}, /* LEFT */
    {357, 1, OS_BOOLEAN|IOC_PIN_PTR, &ioboard_exp, &pins.outputs.RIGHT}, /* RIGHT */
    {358, 1, OS_BOOLEAN|IOC_PIN_PTR, &ioboard_exp, &pins.outputs.FORWARD}, /* FORWARD */
    {359, 1, OS_BOOLEAN|IOC_PIN_PTR, &ioboard_exp, &pins.outputs.BACKWARD} /* BACKWARD */
  },

  {
    {"imp", &ioboard_imp, 13, DEMOCAR_IMP_MBLK_SZ, (iocSignal*)&democar.imp.set_nc_nr},
    {0, 7, OS_STR, &ioboard_imp, OS_NULL}, /* set_nc_nr */
    {8, 24, OS_STR, &ioboard_imp, OS_NULL}, /* set_nc_net */
    {33, 64, OS_STR, &ioboard_imp, OS_NULL}, /* set_nc_connect */
    {98, 16, OS_STR, &ioboard_imp, OS_NULL}, /* set_nc_wifi */
    {115, 16, OS_STR, &ioboard_imp, OS_NULL}, /* set_nc_pass */
    {132, 1, OS_BOOLEAN, &ioboard_imp, OS_NULL}, /* reboot */
    {133, 1, OS_BOOLEAN, &ioboard_imp, OS_NULL}, /* forget_it */
    {134, 1, OS_BOOLEAN, &ioboard_imp, OS_NULL}, /* factory_rst */
    {135, 1, OS_CHAR, &ioboard_imp, OS_NULL}, /* set_rm_comloop */
    {137, 1, OS_BOOLEAN, &ioboard_imp, OS_NULL}, /* LeftTurn */
    {138, 1, OS_BOOLEAN, &ioboard_imp, OS_NULL}, /* RightTurn */
    {139, 1, OS_BOOLEAN, &ioboard_imp, OS_NULL}, /* StraightForward */
    {140, 1, OS_BOOLEAN, &ioboard_imp, OS_NULL} /* ForwardBackward */
  },

  {
    {"conf_exp", &ioboard_conf_exp, 8, DEMOCAR_CONF_EXP_MBLK_SZ, (iocSignal*)&democar.conf_exp.tod_state},
    {0, 1, OS_CHAR, &ioboard_conf_exp, OS_NULL}, /* tod_state */
    {2, 1, OS_UCHAR, &ioboard_conf_exp, OS_NULL}, /* tod_err */
    {4, 1, OS_INT, &ioboard_conf_exp, OS_NULL}, /* tod_tail */
    {9, 1, OS_CHAR, &ioboard_conf_exp, OS_NULL}, /* frd_state */
    {11, 1, OS_UCHAR, &ioboard_conf_exp, OS_NULL}, /* frd_err */
    {13, 1, OS_USHORT, &ioboard_conf_exp, OS_NULL}, /* frd_cs */
    {16, 1, OS_INT, &ioboard_conf_exp, OS_NULL}, /* frd_head */
    {21, 257, OS_UCHAR, &ioboard_conf_exp, OS_NULL} /* frd_buf */
  },

  {
    {"conf_imp", &ioboard_conf_imp, 8, DEMOCAR_CONF_IMP_MBLK_SZ, (iocSignal*)&democar.conf_imp.tod_cmd},
    {0, 1, OS_CHAR, &ioboard_conf_imp, OS_NULL}, /* tod_cmd */
    {2, 1, OS_CHAR, &ioboard_conf_imp, OS_NULL}, /* tod_select */
    {4, 1, OS_USHORT, &ioboard_conf_imp, OS_NULL}, /* tod_cs */
    {7, 1, OS_INT, &ioboard_conf_imp, OS_NULL}, /* tod_head */
    {12, 1025, OS_UCHAR, &ioboard_conf_imp, OS_NULL}, /* tod_buf */
    {1038, 1, OS_CHAR, &ioboard_conf_imp, OS_NULL}, /* frd_cmd */
    {1040, 1, OS_UCHAR, &ioboard_conf_imp, OS_NULL}, /* frd_select */
    {1042, 1, OS_INT, &ioboard_conf_imp, OS_NULL} /* frd_tail */
  }
};

static OS_FLASH_MEM iocMblkSignalHdr * OS_FLASH_MEM democar_mblk_list[] =
{
  &democar.exp.hdr,
  &democar.imp.hdr,
  &democar.conf_exp.hdr,
  &democar.conf_imp.hdr
};

OS_FLASH_MEM iocDeviceHdr democar_hdr = {(iocMblkSignalHdr**)democar_mblk_list, sizeof(democar_mblk_list)/sizeof(iocMblkSignalHdr*)};
