/* This file is generated by bin_to_c.py script, do not modify. */
#ifndef IOC_SIGNALS_INFO_MBLK_INCLUDED
#define IOC_SIGNALS_INFO_MBLK_INCLUDED
OSAL_C_HEADER_BEGINS

extern OS_FLASH_MEM_H os_char ioapp_signals_config[1629];

OSAL_C_HEADER_ENDS
#endif
