/* This file is generated by signals_to_c.py script, do not modify. */
#ifndef IOC_SIGNALS_INCLUDED
#define IOC_SIGNALS_INCLUDED
OSAL_C_HEADER_BEGINS

typedef struct democar_t
{
  struct 
  {
    iocMblkSignalHdr hdr;
    iocSignal nc_nr;
    iocSignal nc_net;
    iocSignal nc_connect;
    iocSignal nc_wifi;
    iocSignal nc_pass;
    iocSignal nc_ip;
    iocSignal nc_status;
    iocSignal si_package;
    iocSignal si_eosal;
    iocSignal si_iocom;
    iocSignal si_os;
    iocSignal si_osver;
    iocSignal si_arch;
    iocSignal si_hw;
    iocSignal rm_malloc;
    iocSignal rm_muse;
    iocSignal rm_threads;
    iocSignal rm_events;
    iocSignal rm_mutexes;
    iocSignal rm_sockets;
    iocSignal rm_connects;
    iocSignal rm_tx_tcp;
    iocSignal rm_rx_tcp;
    iocSignal rm_tx_udp;
    iocSignal rm_rx_udp;
    iocSignal rm_tx_serial;
    iocSignal rm_rx_serial;
    iocSignal rm_aveloop;
    iocSignal rm_maxloop;
    iocSignal rm_boottime;
    iocSignal LEFT;
    iocSignal RIGHT;
    iocSignal FORWARD;
    iocSignal BACKWARD;
  }
  exp;

  struct 
  {
    iocMblkSignalHdr hdr;
    iocSignal set_nc_nr;
    iocSignal set_nc_net;
    iocSignal set_nc_connect;
    iocSignal set_nc_wifi;
    iocSignal set_nc_pass;
    iocSignal reboot;
    iocSignal forget_it;
    iocSignal factory_rst;
    iocSignal set_rm_comloop;
    iocSignal LeftTurn;
    iocSignal RightTurn;
    iocSignal StraightForward;
    iocSignal ForwardBackward;
  }
  imp;

  struct 
  {
    iocMblkSignalHdr hdr;
    iocSignal tod_state;
    iocSignal tod_err;
    iocSignal tod_tail;
    iocSignal frd_state;
    iocSignal frd_err;
    iocSignal frd_cs;
    iocSignal frd_head;
    iocSignal frd_buf;
  }
  conf_exp;

  struct 
  {
    iocMblkSignalHdr hdr;
    iocSignal tod_cmd;
    iocSignal tod_select;
    iocSignal tod_cs;
    iocSignal tod_head;
    iocSignal tod_buf;
    iocSignal frd_cmd;
    iocSignal frd_select;
    iocSignal frd_tail;
  }
  conf_imp;
}
democar_t;

#define DEMOCAR_EXP_MBLK_SZ 360
#define DEMOCAR_IMP_MBLK_SZ 141
#define DEMOCAR_CONF_EXP_MBLK_SZ 279
#define DEMOCAR_CONF_IMP_MBLK_SZ 1047

extern OS_FLASH_MEM_H democar_t democar;
extern OS_FLASH_MEM_H iocDeviceHdr democar_hdr;


/* IO device hardware version. */
#define DEMOCAR_HW "carol"

/* Array length defines. */
#define DEMOCAR_EXP_NC_NR_ARRAY_SZ 8
#define DEMOCAR_EXP_NC_NET_ARRAY_SZ 25
#define DEMOCAR_EXP_NC_CONNECT_ARRAY_SZ 65
#define DEMOCAR_EXP_NC_WIFI_ARRAY_SZ 17
#define DEMOCAR_EXP_NC_PASS_ARRAY_SZ 17
#define DEMOCAR_EXP_NC_IP_ARRAY_SZ 48
#define DEMOCAR_EXP_SI_PACKAGE_ARRAY_SZ 12
#define DEMOCAR_EXP_SI_EOSAL_ARRAY_SZ 7
#define DEMOCAR_EXP_SI_IOCOM_ARRAY_SZ 7
#define DEMOCAR_EXP_SI_OS_ARRAY_SZ 8
#define DEMOCAR_EXP_SI_OSVER_ARRAY_SZ 8
#define DEMOCAR_EXP_SI_ARCH_ARRAY_SZ 8
#define DEMOCAR_EXP_SI_HW_ARRAY_SZ 17
#define DEMOCAR_IMP_SET_NC_NR_ARRAY_SZ 7
#define DEMOCAR_IMP_SET_NC_NET_ARRAY_SZ 24
#define DEMOCAR_IMP_SET_NC_CONNECT_ARRAY_SZ 64
#define DEMOCAR_IMP_SET_NC_WIFI_ARRAY_SZ 16
#define DEMOCAR_IMP_SET_NC_PASS_ARRAY_SZ 16
#define DEMOCAR_CONF_EXP_FRD_BUF_ARRAY_SZ 257
#define DEMOCAR_CONF_IMP_TOD_BUF_ARRAY_SZ 1025

/* Defines to check in code with #ifdef to know if signal is configured in JSON. */
#define DEMOCAR_EXP_NC_NR
#define DEMOCAR_EXP_NC_NET
#define DEMOCAR_EXP_NC_CONNECT
#define DEMOCAR_EXP_NC_WIFI
#define DEMOCAR_EXP_NC_PASS
#define DEMOCAR_EXP_NC_IP
#define DEMOCAR_EXP_NC_STATUS
#define DEMOCAR_EXP_SI_PACKAGE
#define DEMOCAR_EXP_SI_EOSAL
#define DEMOCAR_EXP_SI_IOCOM
#define DEMOCAR_EXP_SI_OS
#define DEMOCAR_EXP_SI_OSVER
#define DEMOCAR_EXP_SI_ARCH
#define DEMOCAR_EXP_SI_HW
#define DEMOCAR_EXP_RM_MALLOC
#define DEMOCAR_EXP_RM_MUSE
#define DEMOCAR_EXP_RM_THREADS
#define DEMOCAR_EXP_RM_EVENTS
#define DEMOCAR_EXP_RM_MUTEXES
#define DEMOCAR_EXP_RM_SOCKETS
#define DEMOCAR_EXP_RM_CONNECTS
#define DEMOCAR_EXP_RM_TX_TCP
#define DEMOCAR_EXP_RM_RX_TCP
#define DEMOCAR_EXP_RM_TX_UDP
#define DEMOCAR_EXP_RM_RX_UDP
#define DEMOCAR_EXP_RM_TX_SERIAL
#define DEMOCAR_EXP_RM_RX_SERIAL
#define DEMOCAR_EXP_RM_AVELOOP
#define DEMOCAR_EXP_RM_MAXLOOP
#define DEMOCAR_EXP_RM_BOOTTIME
#define DEMOCAR_EXP_LEFT
#define DEMOCAR_EXP_RIGHT
#define DEMOCAR_EXP_FORWARD
#define DEMOCAR_EXP_BACKWARD
#define DEMOCAR_IMP_SET_NC_NR
#define DEMOCAR_IMP_SET_NC_NET
#define DEMOCAR_IMP_SET_NC_CONNECT
#define DEMOCAR_IMP_SET_NC_WIFI
#define DEMOCAR_IMP_SET_NC_PASS
#define DEMOCAR_IMP_REBOOT
#define DEMOCAR_IMP_FORGET_IT
#define DEMOCAR_IMP_FACTORY_RST
#define DEMOCAR_IMP_SET_RM_COMLOOP
#define DEMOCAR_IMP_LEFTTURN
#define DEMOCAR_IMP_RIGHTTURN
#define DEMOCAR_IMP_STRAIGHTFORWARD
#define DEMOCAR_IMP_FORWARDBACKWARD
#define DEMOCAR_CONF_EXP_TOD_STATE
#define DEMOCAR_CONF_EXP_TOD_ERR
#define DEMOCAR_CONF_EXP_TOD_TAIL
#define DEMOCAR_CONF_EXP_FRD_STATE
#define DEMOCAR_CONF_EXP_FRD_ERR
#define DEMOCAR_CONF_EXP_FRD_CS
#define DEMOCAR_CONF_EXP_FRD_HEAD
#define DEMOCAR_CONF_EXP_FRD_BUF
#define DEMOCAR_CONF_IMP_TOD_CMD
#define DEMOCAR_CONF_IMP_TOD_SELECT
#define DEMOCAR_CONF_IMP_TOD_CS
#define DEMOCAR_CONF_IMP_TOD_HEAD
#define DEMOCAR_CONF_IMP_TOD_BUF
#define DEMOCAR_CONF_IMP_FRD_CMD
#define DEMOCAR_CONF_IMP_FRD_SELECT
#define DEMOCAR_CONF_IMP_FRD_TAIL

#ifndef IOBOARD_DEVICE_NAME
#define IOBOARD_DEVICE_NAME "democar"
#endif

OSAL_C_HEADER_ENDS
#endif
